return {
  -- {
  --   "zbirenbaum/copilot.lua",
  --   event = "InsertEnter",
  --   cmd = "Copilot",
  --   config = true,
  --   opts = {
  --     suggestion = {
  --       enabled = true,
  --       auto_trigger = false,
  --       hide_during_completion = true,
  --       debounce = 75,
  --       keymap = {
  --         accept = "<C-]>",
  --         accept_word = false,
  --         accept_line = false,
  --         next = "<M-]>",
  --         prev = "<M-[>",
  --         dismiss = "<C-[>",
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "CopilotC-Nvim/CopilotChat.nvim",
  --   branch = "canary",
  --   dependencies = {
  --     { "zbirenbaum/copilot.lua" }, -- or github/copilot
  --     { "nvim-lua/plenary.nvim" },  -- for curl, log wrapper
  --   },
  --   config = true,
  --   keys = {
  --     {
  --       "<leader>ccq",
  --       function()
  --         local input = vim.fn.input("Quick Chat: ")
  --         if input ~= "" then
  --           require("CopilotChat").ask(input, { selection = require("CopilotChat.select").buffer })
  --         end
  --       end,
  --       desc = "CopilotChat - Quick chat",
  --     },
  --     {
  --       "<leader>ccc", "<cmd>lua require('CopilotChat').toggle()<cr>", desc = "CopilotChat - Toggle",
  --     },
  --     {
  --       "C", "<cmd>lua require('CopilotChat').toggle()<cr>", desc = "CopilotChat - Toggle",
  --     }
  --   }
  -- }
}
